### PR TITLE
Connect frontend backend planner

### PR DESCRIPTION
**Pull request by nelsondude**
Must run the SQL script in the root of the project to populate the database with the necessary fields.

### CODE REVIEW

**Comment by anushav101** [comment]
we might want to change the total points to automatically update as the planned action changes

**Comment by nelsondude** [comment]
Are you talking about on the profile page? Like after you delete a planned item

**Comment by nelsondude** [comment]
Also, it seems that for some of the actions, the value for points is either a range or it says "Points vary". How should we account for this when summing up the total number of points planned?

**Review by songyh1996 — APPROVED** [review]
Very nice!

**Pull request merged**
